version: '3.9'

services:
  customer-webchat:
    image: crccheck/hello-world
    ports:
      - "8010:8000"
    configs:
      - source: crccheck_v2
        target: /www/index.html
    # volumes:
    #   - /mnt/dockervol1/customer_webchats:/www
    networks:
      - stubber
# This is a comment

configs:
  crccheck_v2:
    external: true

networks:
  stubber:
    external: true

    
