version: '3.9'

services:
  customer-webchat:
    image: crccheck/hello-world
    ports:
      - "8888:8000"
    # volumes:
    #   - /mnt/dockervol1/customer_webchats:/www
    networks:
      - stubber

networks:
  stubber:
    external: true
